travis:
  secure:
    BINSTAR_TOKEN: nswbmvGDhwSJhac7yk7Ljf4FEgQpuIOsKNmmUXc12XR5YT0E6YQk8qRRC8UwOx7Vd6VVkLCG9KgxSDMnpbvlQR/txJWh1ukFtndKTx2dIuc0IL0HS/ylV23isJ+hZt+DcbIMVkcsip35WMXZ9VsbT6QsvYFeUbf8bOX0bf/Jcmt0tWTrPURGt/5gqe3s2YNPAdSJEMi3FNzmfVu7yAMFp562hGtcIgK8kmmH1wfYtSy9YLQZ+kAua3RnBL8Vq2RZP+d3n5jBs7PAHcIqjxSgRz+FSCdNFSK108s1tuvUg23QtFbJqngtJk9TN2aPrQHmIPoL75bWMewGos85MltrypP286mTJAYjKSkeeLJPdVXcloxk9xgXyuc76nTIkvfyDfgWT3mOUes/lXhpEnnYwbXjkoFzFrLlV+q0VbO0etxPoMbc60F2jlbnuj1+EHGxI6gv/8rme+6gjFstS49UZPnjw4AagmY3V6X+skNtdWyhQzRhxmuTdJVz3/C5YTE6cDafQgLK0qlET8iM8Edy0HEiAOU7Uy/87ci9MEqfLX3KPhlGlaqn5vaDVaZbthMtluMgK4DkZwUR92jvVX8F68F57f/wB9OkhyfEIswk2/JVeHLQdPipatX1xsxpuUp/RE/vThsOVCOLHIUP1jv7gra3FxIqxmODbulExj5aQlw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
